### ISSUE TITLE
Doesn't appear to work anymore

### ISSUE THREAD

**Issue by Deanosim** [nokusukun/DCSE#1]
No option for entering the password and ..cse doesn't appear to do anything

**Comment by tomh4x** [comment]
seconded.  does not work.  no UI change appears on install.

**Comment by nokusukun** [comment]
Huh, I wasn't aware that this was still being sought out. I might push a fix since this hasn't been updated for over a year now.

**Comment by nokusukun** [comment]
Pushed a fix, it should be working though there's some caveats as explained in "Issues".
